apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: default
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"            
        memory: "2Gi"         
      defaultRequest:
        cpu: "250m"
        memory: "1G"       
