apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: default
spec:
  hard:
    requests.cpu: "5"       
    requests.memory: "10Gi" 
    limits.cpu: "5"         
    limits.memory: "10Gi"   

